name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust-version: [stable]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Clone src-dst-clarifier
      run: git clone https://github.com/eternal-io/src-dst-clarifier.git
    - name: Clone kalavor
      run: git clone https://github.com/eternal-io/kalavor.git
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust-version }}
    - name: Add src-dst-clarifier as a dependency
      run: cargo add --path ./src-dst-clarifier
    - name: Add kalavor as a dependency
      run: cargo add --path ./kalavor
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test
